### ISSUE TITLE
API to retrieve root setting

### ISSUE THREAD

**Issue by yrutschle** [cnangel/Conf-Libconfig#2]
It used to be possible to retrieve the entirety of the configuration as a hash doing:
```
$conf->fetch_hashref("/");
```

This no longer works in libconfig 1.7.3 (https://github.com/hyperrealm/libconfig/issues/196), and Conf::Libconfig has no API that translates to `config_root_setting()`, so you cannot get to the root and, e.g., enumerate settings you don't know.

**Comment by cnangel** [comment]
Yes, and had fixed.
